language: node_js
node_js:
  - 4.2.3
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 5.1.1
before_script:
  - npm install -g bower grunt-cli
  - bower install
services: mongodb
#deploy:
#  provider: heroku
#  api_key:
    #secure: "87d3ff8d-1fd5-46df-a11f-d64b4848a8db"
